version: "3.8"
#  docker volume create --name minecraftdata 
services:
  mc:
    image: itzg/minecraft-server
    container_name: minecraft-docker
    environment:
      OVERRIDE_SERVER_PROPERTIES: "false"
      VERSION: "1.19.3"
      EULA: "true"
      TYPE: "PAPER"
      PAPERBUILD: "431"
      MEMORY: "3G"
    ports:
      - "25565:25565"
    networks:
      - mincraft_default
    volumes:
      - ./minecraftdata:/data
      - ./plugins:/plugins
    stdin_open: true
    tty: true
    restart: unless-stopped

networks:
  mincraft_default:
    name: mincraft_default
    external: true
